# TCL File Generated by Component Editor 9.0
# Mon Nov 20 08:24:52 ACT 2017
# DO NOT MODIFY


# +-----------------------------------
# | 
# | can_opener "can_opener" v1.0
# | null 2017.11.20.08:24:52
# | 
# | 
# | C:/Users/joseb/Dropbox/FING/DisLog2/Proyecto/05_Final/ip/can_opener.vhd
# | 
# |    ./can_opener.vhd syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module can_opener
# | 
set_module_property NAME can_opener
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP Can
set_module_property DISPLAY_NAME can_opener
set_module_property LIBRARIES {ieee.std_logic_1164.all ieee.numeric_std.all std.standard.all}
set_module_property TOP_LEVEL_HDL_FILE can_opener.vhd
set_module_property TOP_LEVEL_HDL_MODULE can_opener
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file can_opener.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end
set_interface_property clock_reset ptfSchematicName ""

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset clk clk Input 1
add_interface_port clock_reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point slave
# | 
add_interface slave avalon end
set_interface_property slave addressAlignment DYNAMIC
set_interface_property slave bridgesToMaster ""
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave holdTime 0
set_interface_property slave isMemoryDevice false
set_interface_property slave isNonVolatileStorage false
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave printableDevice false
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0

set_interface_property slave ASSOCIATED_CLOCK clock_reset
set_interface_property slave ENABLED true

add_interface_port slave slave_address address Input 2
add_interface_port slave slave_read read Input 1
add_interface_port slave slave_write write Input 1
add_interface_port slave slave_readdata readdata Output 32
add_interface_port slave slave_writedata writedata Input 32
add_interface_port slave slave_byteenable byteenable Input 4
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ASSOCIATED_CLOCK clock_reset
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end can_rx export Input 1
# | 
# +-----------------------------------
