# TCL File Generated by Component Editor 9.0
# Mon Oct 23 17:49:03 ACT 2017
# DO NOT MODIFY


# +-----------------------------------
# | 
# | can_opener "can_opener" v1.0
# | null 2017.10.23.17:49:03
# | 
# | 
# | C:/Users/joseb/Dropbox/FING/DisLog2/Proyecto/04_Nios/Helloworld/ip/Can_Opener/can_opener.vhd
# | 
# |    ./can_opener.vhd syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module can_opener
# | 
set_module_property NAME can_opener
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP Can
set_module_property DISPLAY_NAME can_opener
set_module_property LIBRARIES {ieee.std_logic_1164.all ieee.numeric_std.all ieee.numeric_std.all std.standard.all}
set_module_property TOP_LEVEL_HDL_FILE can_opener.vhd
set_module_property TOP_LEVEL_HDL_MODULE can_opener
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file can_opener.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end
set_interface_property clock_reset ptfSchematicName ""

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset clk clk Input 1
add_interface_port clock_reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 bridgesToMaster ""
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ASSOCIATED_CLOCK clock_reset
set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 slave_address address Input 2
add_interface_port avalon_slave_0 slave_read read Input 1
add_interface_port avalon_slave_0 slave_write write Input 1
add_interface_port avalon_slave_0 slave_readdata readdata Output 32
add_interface_port avalon_slave_0 slave_writedata writedata Input 32
add_interface_port avalon_slave_0 slave_byteenable byteenable Input 4
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ASSOCIATED_CLOCK clock_reset
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end can_address export Input 11
add_interface_port conduit_end can_length export Input 4
add_interface_port conduit_end can_data export Input 64
add_interface_port conduit_end can_crc export Input 1
add_interface_port conduit_end can_estado export Output 4
add_interface_port conduit_end fifo_empty export Input 1
add_interface_port conduit_end fifo_full export Input 1
add_interface_port conduit_end fifo_read export Output 1
# | 
# +-----------------------------------
